/**
 * Generated by Agitar build: JUnitFactory Version 2.1.0.000576 (Build date: Oct 19, 2007) [2.1.0.000576]
 * JDK Version: 1.5.0_11
 *
 * Generated on Nov 8, 2007 5:49:40 PM
 * Time to generate: 00:14.320 seconds
 *
 */

package org.mentawai.template;

import com.agitar.lib.junit.AgitarTestCase;
import org.mentawai.util.RuntimeException;

public class TemplateExceptionAgitarTest extends AgitarTestCase {
    
    public Class getTargetClass()  {
        return TemplateException.class;
    }
    
    public void testConstructor() throws Throwable {
        TemplateException templateException = new TemplateException("testTemplateExceptionMessage");
        assertNull("templateException.getCause()", templateException.getCause());
        assertEquals("templateException.getMessage()", "testTemplateExceptionMessage", templateException.getMessage());
    }
    
    public void testConstructor1() throws Throwable {
        Throwable e = new NumberFormatException();
        TemplateException templateException = new TemplateException(e);
        assertSame("templateException.getCause()", e, templateException.getCause());
        assertSame("templateException.getCause()", e, templateException.getCause());
        assertEquals("templateException.getMessage()", "java.lang.NumberFormatException", templateException.getMessage());
        // dependencies on static and environment state led to removal of 1 assertion
    }
    
    public void testConstructorThrowsNullPointerException() throws Throwable {
        try {
            new TemplateException((Throwable) null);
            fail("Expected NullPointerException to be thrown");
        } catch (NullPointerException ex) {
            assertNull("ex.getMessage()", ex.getMessage());
            assertThrownBy(RuntimeException.class, ex);
        }
    }
}

