/**
 * Generated by Agitar build: JUnitFactory Version 2.1.0.000576 (Build date: Oct 19, 2007) [2.1.0.000576]
 * JDK Version: 1.5.0_11
 *
 * Generated on Nov 8, 2007 7:27:11 PM
 * Time to generate: 00:14.213 seconds
 *
 */

package org.mentawai.core;

import com.agitar.lib.junit.AgitarTestCase;

public class InputExceptionAgitarTest extends AgitarTestCase {
    
    public Class getTargetClass()  {
        return InputException.class;
    }
    
    public void testConstructor() throws Throwable {
        Exception e = new NumberFormatException();
        InputException inputException = new InputException(e);
        assertSame("inputException.getCause()", e, inputException.getCause());
        assertEquals("inputException.getMessage()", "java.lang.NumberFormatException", inputException.getMessage());
        // dependencies on static and environment state led to removal of 1 assertion
    }
    
    public void testConstructor1() throws Throwable {
        new InputException();
        assertTrue("Test call resulted in expected outcome", true);
    }
    
    public void testConstructor2() throws Throwable {
        InputException inputException = new InputException("testInputExceptionMsg");
        assertEquals("inputException.getMessage()", "testInputExceptionMsg", inputException.getMessage());
    }
    
    public void testConstructorThrowsNullPointerException() throws Throwable {
        try {
            new InputException((Exception) null);
            fail("Expected NullPointerException to be thrown");
        } catch (NullPointerException ex) {
            assertNull("ex.getMessage()", ex.getMessage());
            assertThrownBy(InputException.class, ex);
        }
    }
}

